In [46]:
import numpy as np
from collections import deque

In [47]:
def possible_moves(start):
    # Initialize an empty list to store possible moves
    moves = []
    
    # Get the number of rows and columns in the input matrix
    rows, cols = start.shape
    
    # Find the indices of the zero element in the matrix
    zero = np.where(start == 0)
    
    # Check if moving up is a valid move (if the zero element is not in the first row)
    if zero[0] > 0:
        # Add the coordinates of the element above the zero element to the list of moves
        moves.append((zero[0] - 1, zero[1]))
    
    # Check if moving left is a valid move (if the zero element is not in the first column)
    if zero[1] > 0:
        # Add the coordinates of the element to the left of the zero element to the list of moves
        moves.append((zero[0], zero[1] - 1))
    
    # Check if moving down is a valid move (if the zero element is not in the last row)
    if zero[0] < rows - 1:
        # Add the coordinates of the element below the zero element to the list of moves
        moves.append((zero[0] + 1, zero[1]))
    
    # Check if moving right is a valid move (if the zero element is not in the last column)
    if zero[1] < cols - 1:
        # Add the coordinates of the element to the right of the zero element to the list of moves
        moves.append((zero[0], zero[1] + 1))
    
    # Return the list of possible moves
    return moves

        

In [48]:
def generate_successors(start):
    # Find the indices of the zero element in the matrix
    zero = np.where(start == 0)
    
    # Initialize an empty list to store the successors
    successors = []
    
    # Get possible moves for the current state
    moves = possible_moves(start)
    
    # Iterate over each possible move
    for move in moves:
        # Create a copy of the current state to generate a successor
        successor = start.copy()
        
        # Swap the zero element with the element at the move position
        successor[zero[0], zero[1]] = successor[move[0], move[1]]
        successor[move[0], move[1]] = 0
        
        # Add the successor to the list of successors
        successors.append(successor)
    
    # Return the list of successors
    return successors


In [49]:
def heuristics(start, goal):
    # Initialize distance as 0
    distance = 0
    
    # Iterate over each cell in the start state
    for i in range(start.shape[0]):
        for j in range(start.shape[1]):
            # Get the value at the current cell
            value = start[i, j]
            
            # Check if the value is not 0 (as we don't calculate distance for the empty space)
            if value != 0:
                # Find the position of the value in the goal state
                goal_position = np.where(goal == value)
                
                # Calculate Manhattan distance between the current cell in start and its corresponding cell in goal
                distance += abs(i - goal_position[0]) + abs(j - goal_position[1])
    
    # Return the total Manhattan distance
    return distance



In [51]:
from collections import deque

def GreedyBestFirstSearch(start, goal):
    # Set to keep track of visited states
    visited = set()
    
    # Initialize the queue with the start state and an empty path
    queue = deque([(start, [])])
    
    # Loop until the queue is empty
    while queue:
        # Sort the queue based on heuristic values of states
        queue = deque(sorted(queue, key=lambda x: heuristics(x[0], goal)))
        
        # Pop the state with the lowest heuristic value
        current_state, path = queue.popleft()
        
        # Convert current state to a tuple and add it to visited set
        visited.add(tuple(current_state.flatten()))
        
        # Check if the current state is the goal state
        if np.array_equal(current_state, goal):
            return path
        
        # Generate successors for the current state
        successors = generate_successors(current_state)
        
        # Iterate over each successor
        for successor in successors:
            # Convert successor to a tuple
            successor_tuple = tuple(successor.flatten())
            
            # Check if the successor state has not been visited
            if successor_tuple not in visited:
                # Add the successor state and the updated path to the queue
                queue.append((successor, path + [successor]))
    
    # If no solution is found, return None
    return None

# Define start and goal states
start = np.array([[1, 2, 3], [0, 4, 6], [7, 5, 8]])
goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

# Find the solution path using Greedy Best First Search
solution_path = GreedyBestFirstSearch(start, goal)

# Print the solution path
if solution_path:
    for i, state in enumerate(solution_path):
        print(i + 1, ":")
        print("State:")
        print(state)
        print("Heuristic:", heuristics(state, goal))
else:
    print("No solution")


                
        
    

1 :
State:
[[1 2 3]
 [4 0 6]
 [7 5 8]]
 Heuristic: [2]
2 :
State:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
 Heuristic: [1]
3 :
State:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
 Heuristic: [0]
